management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,retries,retryevents,env,heapdump

resilience4j:
  retry:
    instances:
      downstream:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 1
        retryExceptions:
          - java.io.IOException
  timeLimiter:
    configs:
      default:
        timeoutDuration: 5s
        eventConsumerBufferSize: '100'
        cancelRunningFuture: 'true'
    instances:
      downstream:
        timeoutDuration: 2s
        cancelRunningFuture: true

timeLimit:
  default: 5s
